### ISSUE TITLE
Angular 2 Final - has no exported member 'provide' or 'Type'

### ISSUE THREAD

**Issue by blubberbo** [marcj/angular2-localStorage#66]
I am running the Angular 2 Final release ^2.0.2 and angular2-localstorage is giving the following errors in the file "LocalStorageEmitter.ts":

"/node_modules/@angular/core/src/facade/lang" has no exported member 'Type'
"/node_modules/@angular/core/src/di" has no exported member 'provide'

I just installed angular2-localstorage from npm, so I have latest.

Any experiencing the same issue?

Thanks

**Comment by fivepapertigers** [comment]
+1

**Comment by radarsu** [comment]
Same error.

**Comment by qvantor** [comment]
I got same error

**Comment by vzt1** [comment]
same here..is there any workaround/fix?

**Comment by daveksb** [comment]
I found the same error too.

**Comment by qvantor** [comment]
https://github.com/btroncone/ngrx-store-localstorage
this is better

**Comment by woutrbe** [comment]
I've gotten the same issue when following the basic instructions, is there any fix in sight for Angular 2 Final?

**Comment by radarsu** [comment]
You can try to use https://github.com/radarsu/angular2-localstorage. I fixed some minor issues there.

**Comment by marcj** [comment]
Merged angular-2.0.0 fixes. Please try again with master version.

**Comment by hsaklecha** [comment]
Getting this now, when i started using it :
I am using latest version for angular and other dependencies

ERROR in [default] c:\Repository\xyz\node_modules\angular2-localstorage\LocalStorageEmitter.ts:46:8
Module '"c:/Repository/xyz/node_modules/@angular/core/src/facade/lang"' has no exported member 'Type'.

ERROR in [default] c:\Repository\xyz\node_modules\angular2-localstorage\LocalStorageEmitter.ts:47:8
Module '"c:/Repository/xyz/node_modules/@angular/core/src/di"' has no exported member 'provide'.

ERROR in [default] c:\Repository\xyz\src\app\app.module.ts:3:54
Cannot find module 'angular2-localstorage'.

**Comment by hsaklecha** [comment]
Is this issue resolved, i am still getting error

**Comment by mdopieralski** [comment]
angular 2.4.6 x angular2-localstorage 0.4.0 => still occuring

**Comment by jelling** [comment]
+1

**Comment by SuTran** [comment]
+1

**Comment by DanielKucal** [comment]
My fork of [angular2-localstorage](https://github.com/zoomsphere/angular2-localstorage/) works pretty well with newest Angular2 version and has some extra features (with no breaking changes) listed in README. Hope you'll enjoy it :)

**Comment by venikx** [comment]
@hsaklecha @mdopieralski @jelling @SuTran This is probably, because you are installing this library using npm, for whatever reason the github version and npm version seem out-of-sync.

**Comment by rangelke** [comment]
@DanielKucal 
How compatible is your fork with this one (we are pretty deep into a project and looking for alternative options without breaking too much)

**Comment by chopada** [comment]
Replace this lines from "LocalStorageEmitter.ts" from node_modeule "angular2-localstorage"

```
import {Type} from "@angular/core/src/facade/lang";
import {provide} from "@angular/core/src/di";
import {ComponentRef} from "@angular/core";

export function LocalStorageSubscriber(appPromise: Promise<ComponentRef<any>>) {
    appPromise.then((bla) => {
        bla.injector.get(<Type>LocalStorageService);
    });
}
```

with this.

```
import {Type} from "@angular/core/src/type";
import {Provider} from "@angular/core/src/di";
import {ComponentRef} from "@angular/core";

export function LocalStorageSubscriber(appPromise: Promise<ComponentRef<any>>) {
    appPromise.then((bla) => {
        bla.injector.get(<Type<any>>LocalStorageService);
    });
}
```

It's Works for me...

**Comment by fToledo29** [comment]
Thanks @chopada , it works for me.

**Comment by YannikHsKA** [comment]
Thanks @chopada , worked for me as well.
